version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      all-dependencies-but-not-node-types:
        applies-to: version-updates
        patterns:
          - "*"
        exclude-patterns:
          - "@types/node"
